"""empty message

Revision ID: c94d8577c987
Revises: f4288106196c
Create Date: 2016-01-24 00:47:52.681328

"""

# revision identifiers, used by Alembic.
revision = 'c94d8577c987'
down_revision = 'f4288106196c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridges', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_column('fridges', 'quality')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridges', sa.Column('quality', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('fridges', 'quantity')
    ### end Alembic commands ###
