"""empty message

Revision ID: f4288106196c
Revises: None
Create Date: 2016-01-23 15:39:38.836261

"""

# revision identifiers, used by Alembic.
revision = 'f4288106196c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridges', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_column('fridges', 'quality')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridges', sa.Column('quality', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('fridges', 'quantity')
    ### end Alembic commands ###
